// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_astronomical = "CgkIwYGYnuAFEAIQFA"; // <GPGSID>
        public const string achievement_veteran_collector = "CgkIwYGYnuAFEAIQDA"; // <GPGSID>
        public const string achievement_astounding_adventurer = "CgkIwYGYnuAFEAIQBA"; // <GPGSID>
        public const string achievement_wise_wanderer = "CgkIwYGYnuAFEAIQAg"; // <GPGSID>
        public const string achievement_talented_traveller = "CgkIwYGYnuAFEAIQCA"; // <GPGSID>
        public const string achievement_astro_veteran = "CgkIwYGYnuAFEAIQEw"; // <GPGSID>
        public const string achievement_astro_novice = "CgkIwYGYnuAFEAIQEA"; // <GPGSID>
        public const string achievement_ultimate_collector = "CgkIwYGYnuAFEAIQDQ"; // <GPGSID>
        public const string achievement_epic_excursionist = "CgkIwYGYnuAFEAIQBQ"; // <GPGSID>
        public const string achievement_astro_starter = "CgkIwYGYnuAFEAIQDg"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIwYGYnuAFEAIQFQ"; // <GPGSID>
        public const string achievement_experienced_explorer = "CgkIwYGYnuAFEAIQCQ"; // <GPGSID>
        public const string achievement_astro_nerd = "CgkIwYGYnuAFEAIQEg"; // <GPGSID>
        public const string achievement_valiant_vagabond = "CgkIwYGYnuAFEAIQBg"; // <GPGSID>
        public const string achievement_astro_gamer = "CgkIwYGYnuAFEAIQEQ"; // <GPGSID>
        public const string achievement_amateur_collector = "CgkIwYGYnuAFEAIQCw"; // <GPGSID>
        public const string achievement_astro_learner = "CgkIwYGYnuAFEAIQDw"; // <GPGSID>
        public const string achievement_serious_sailor = "CgkIwYGYnuAFEAIQBw"; // <GPGSID>
        public const string achievement_novice_collector = "CgkIwYGYnuAFEAIQCg"; // <GPGSID>
        public const string achievement_venerable_voyager = "CgkIwYGYnuAFEAIQAw"; // <GPGSID>

}

